name: My first workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-lastest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.1
    
        - name: welcome message
          run: echo "My first github actions job"

        - name: list files
          run: ls

        - name: Read file
          run: cat README.md
