name:  Generate ASCII Artwork

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-lastest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: list Repo File
          run: ls -itra
        
        - name: Excuting Shell Script
          run: |
           chmod +x acil-script.sh
            ./acil-script.sh

            

      